# Generated by Django 4.1.4 on 2025-02-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_sp_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_product',
            name='image',
            field=models.ImageField(blank=True, upload_to='dbimg'),
        ),
    ]
